theme: minima
title: Jackmanimation
author: Denis Jackman
description: "This is a Test site Jackmanimation Studios!"
github_username: denisjackman
twitter_username: denisjackman
email: denis_jackman@hotmail.com